
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 7;
  public static final int OP_AND = 32;
  public static final int CONTINUE = 16;
  public static final int OP_ASSIGN_DIV = 38;
  public static final int CONST_NUM = 18;
  public static final int PAR_LEFT = 45;
  public static final int FOR = 14;
  public static final int BRACKET_RIGHT = 48;
  public static final int OP_INC = 40;
  public static final int BRACKET_LEFT = 47;
  public static final int OP_DIV = 24;
  public static final int STATIC = 3;
  public static final int PAR_RIGHT = 46;
  public static final int CONST_CHAR = 19;
  public static final int OP_ASSIGN_MUL = 37;
  public static final int COMMA = 43;
  public static final int OP_ASSIGN_ADD = 35;
  public static final int CLASS = 5;
  public static final int OP_ASSIGN_MOD = 39;
  public static final int OP_MUL = 23;
  public static final int IF = 8;
  public static final int OP_ADD = 21;
  public static final int DOT = 44;
  public static final int OP_MOD = 25;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int OP_GTE = 30;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int OP_GREAT = 28;
  public static final int OP_OR = 33;
  public static final int BREAK = 4;
  public static final int CONST_BOOL = 20;
  public static final int IDENT = 17;
  public static final int OP_ASSIGN = 34;
  public static final int VOID = 13;
  public static final int SEMI_COLUMN = 42;
  public static final int ELSE = 6;
  public static final int OP_LESS = 29;
  public static final int READ = 11;
  public static final int OP_ASSIGN_SUB = 36;
  public static final int OP_DEC = 41;
  public static final int EXTENDS = 15;
  public static final int OP_SUB = 22;
  public static final int OP_EQ = 26;
  public static final int OP_NOT_EQ = 27;
  public static final int BRACE_RIGHT = 50;
  public static final int OP_LTE = 31;
  public static final int PRINT = 10;
  public static final int BRACE_LEFT = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "STATIC",
  "BREAK",
  "CLASS",
  "ELSE",
  "CONST",
  "IF",
  "NEW",
  "PRINT",
  "READ",
  "RETURN",
  "VOID",
  "FOR",
  "EXTENDS",
  "CONTINUE",
  "IDENT",
  "CONST_NUM",
  "CONST_CHAR",
  "CONST_BOOL",
  "OP_ADD",
  "OP_SUB",
  "OP_MUL",
  "OP_DIV",
  "OP_MOD",
  "OP_EQ",
  "OP_NOT_EQ",
  "OP_GREAT",
  "OP_LESS",
  "OP_GTE",
  "OP_LTE",
  "OP_AND",
  "OP_OR",
  "OP_ASSIGN",
  "OP_ASSIGN_ADD",
  "OP_ASSIGN_SUB",
  "OP_ASSIGN_MUL",
  "OP_ASSIGN_DIV",
  "OP_ASSIGN_MOD",
  "OP_INC",
  "OP_DEC",
  "SEMI_COLUMN",
  "COMMA",
  "DOT",
  "PAR_LEFT",
  "PAR_RIGHT",
  "BRACKET_LEFT",
  "BRACKET_RIGHT",
  "BRACE_LEFT",
  "BRACE_RIGHT"
  };
}

